export const TOAST = {
  HIDE_TOAST: 'HIDE_TOAST',
  SHOW_TOAST: 'SHOW_TOAST',
}

export const AUTH = {
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
}

