export const TOAST = {
  HIDE_TOAST: 'HIDE_TOAST',
  SHOW_TOAST: 'SHOW_TOAST',
}

export const AUTH = {
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  CHECK_USER_STATE_SUCCESS: 'CHECK_USER_STATE_SUCCESS',
}

export const PROFILE = {
  FETCH_PROFILE_SUCCESS: 'FETCH_PROFILE_SUCCESS',
  BOOST_SCORE_SUCCESS: 'BOOST_SCORE_SUCCESS',
}

export const USER_FEED = {
  FETCH_USER_FEED_SUCCESS: 'FETCH_USER_FEED_SUCCESS',
}

export const HOME_FEED = {
  FETCH_HOME_FEED_SUCCESS: 'FETCH_HOME_FEED_SUCCESS',
}
